import Head from 'next/head';

import AppNavBar from './components/AppNavBar';
import AppCardBullets from './components/AppCardBullets';

export default function Home() {

  let title = "Meu primeiro Web App - Maria Luiza";
  const bullets_today = [
    {type: 'event',title: 'Momento síncrono sobre componente react'},
    {type: 'task',title: 'Palavras chaves - bullet journal, github issues'}
  ];

  const bullets_tomorrow = [
    {type: 'task',title: 'Momento síncrono sobre componente react'},
    {type: 'task',title: 'Palavras chaves - bullet journal, github issues'}
  ];

  return (
    
    <div >
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
      <AppNavBar title={title} />
      <AppCardBullets date={"15/09/2021"} bullets={bullets_today} />
      <AppCardBullets date={"22/09/2021"} bullets={bullets_tomorrow}/>
      </main>

    </div>
  )
}
